Basic Neural Network Implementation on Xilinx PYNQ Z2 Board

import Library

In [66]:
import numpy as np

Get the Data

In [67]:
a=np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
b= np.array([[0,1,1,0]]).T

Make Weights for connection 

In [68]:
wgt0=2*np.random.random((3,4))-1
wgt1=2*np.random.random((4,1))-1

In [69]:
for itr in range(60000):
    #Activation function that acts for input and 1st hidden layer
    lay1=1/(1+np.exp(-np.dot(a,wgt0)))
    #Activation function that acts for 1st hidden layer and 2nd hidden layer
    lay2=1/(1+np.exp(-np.dot(lay1,wgt1)))
    #Gradient Calculation
    lay2_delta=(b-lay2)*(lay2*(1-lay2))
    lay1_delta=lay2_delta.dot(wgt1.T)*(lay1*(1-lay1))
    #weights updates
    wgt1+=lay1.T.dot(lay2_delta)
    wgt0+=a.T.dot(lay1_delta)
                      

In [70]:
wgt0

array([[ 2.24646577, -6.31523923, -6.93627868,  1.15669711],
       [ 2.19247259,  7.14746173,  5.99962009, -2.14884278],
       [ 0.62730854,  3.13657504, -2.9520311 , -0.58343527]])

In [71]:
wgt1

array([[  4.48236463],
       [-10.70395691],
       [ 12.34504401],
       [  2.60369287]])

In [72]:
a_test=[1,1,0]
output_first_layer=np.dot(a_test,w0)

In [73]:
final_output=np.dot(output_first_layer,w1)

In [74]:
final_output

array([-1.30059205])